// src/lib/mock-exam-ehrm.ts
import { registerMockExam, type MockExam } from './mock-exam'

const exam: MockExam = {
  parts: [
    {
      id: 'A',
      title: 'Part A — HR Organization, HRIS & Workflow Management',
      points: 30,
      tasks: [
        {
          kind: 'choice', id: 'A1', type: 'single', points: 3,
          text: 'A bank rolls out a digital HR strategy. Which statement about HR strategy is correct?',
          options: [
            'A successful digital HR strategy balances the "what" (agenda) and the "how" (execution).',
            'The conventional path is to invest heavily in technology first.',
            'HR teams should focus on the "what" and neglect the "how".',
            'Tactical objectives describe the economic and social goals of HRM.',
            'There is no truly successful HR strategy.',
          ],
          correct: [0],
          explanation: 'A successful digital HR strategy balances the WHAT (digital agenda) and the HOW (execution). Tactical objectives describe how formal objectives are achieved; formal objectives include the economic and social goals.',
        },
        {
          kind: 'choice', id: 'A2', type: 'single', points: 3,
          text: 'FAUBank is redesigning its HR department. The head of HR argues that HRM encompasses all employment-related decisions. Which definition of HRM is most complete?',
          options: [
            'HRM includes all decisions, activities and practices that directly affect the people who work in the organisation.',
            'HRM is a department responsible for hiring and firing employees only.',
            'HRM covers only the administrative tasks of managing employee records.',
            'HRM is limited to training and development of employees.',
            'HRM primarily handles compensation and benefits for staff.',
          ],
          correct: [0],
          explanation: 'HRM encompasses all decisions, activities, and practices that directly affect the people working in the organisation — a broad definition that includes strategy, staffing, development, compensation, and more.',
        },
        {
          kind: 'choice', id: 'A3', type: 'single', points: 3,
          text: 'In the three-layer model of HRM systems, which combination correctly pairs a work system element, its supporting information system, and its application system?',
          options: [
            'Time management (work system) → attendance data (IS) → time-tracking software (AS).',
            'Performance appraisal (work system) → payroll data (IS) → ERP financials (AS).',
            'Recruitment (work system) → general-ledger data (IS) → talent software (AS).',
            'Training delivery (work system) → sales data (IS) → CRM system (AS).',
            'Career planning (work system) → inventory data (IS) → supply-chain software (AS).',
          ],
          correct: [0],
          explanation: 'In the three-layer model, work systems define HRM processes, information systems supply the data, and application systems are the software tools. Time management as a work system is naturally supported by attendance data and time-tracking software.',
        },
        {
          kind: 'choice', id: 'A4', type: 'multiple', points: 3,
          text: 'The work-system framework has six core elements. Which TWO of the following are genuine elements of a work system?',
          options: [
            'Participants',
            'Profit margin',
            'Processes & activities',
            'Marketing strategy',
            'Stock price',
          ],
          correct: [0, 2],
          explanation: 'A work system\'s six elements are: customers, products & services, processes & activities, participants, information, and technology. "Participants" and "Processes & activities" are two of these; profit margin, marketing strategy, and stock price are not.',
        },
        {
          kind: 'choice', id: 'A5', type: 'single', points: 3,
          text: 'An HR auditor asks what personal data means in an HRIS context. Which statement is correct?',
          options: [
            'Personal data in an HRIS refers to all information that can be used to identify a specific individual employee.',
            'Personal data only includes payroll and tax information.',
            'Personal data in an HRIS is limited to biometric records.',
            'Personal data refers to anonymised aggregate workforce statistics.',
            'Personal data covers only contact details such as address and phone number.',
          ],
          correct: [0],
          explanation: 'In the context of HRIS, personal data is any information that directly or indirectly identifies a specific individual — covering name, ID number, performance ratings, health records, and more.',
        },
        {
          kind: 'choice', id: 'A6', type: 'single', points: 3,
          text: 'FAUBank\'s HR director states that "tactical objectives describe how we achieve our formal objectives." Which statement best distinguishes formal from tactical HRM objectives?',
          options: [
            'Formal objectives state the economic and social goals of HRM; tactical objectives specify how those goals are pursued.',
            'Formal objectives are short-term targets; tactical objectives are long-term aspirations.',
            'Formal objectives relate to individual employee goals; tactical objectives relate to team goals.',
            'Tactical objectives are legally mandated; formal objectives are self-imposed.',
            'Both types are identical; the labels are interchangeable.',
          ],
          correct: [0],
          explanation: 'Formal objectives in HRM express the economic and social goals (e.g., cost efficiency, fair treatment). Tactical objectives describe how those formal objectives are reached (e.g., specific policies, processes, and systems).',
        },
        {
          kind: 'choice', id: 'A7', type: 'single', points: 3,
          text: 'At what organisational level does workflow management primarily operate?',
          options: [
            'Operational level — coordinating day-to-day task sequences across people and systems.',
            'Strategic level — setting long-range technology investment plans.',
            'Financial level — allocating budget across cost centres.',
            'Governance level — defining board-level HR policy.',
            'Analytical level — building predictive workforce models.',
          ],
          correct: [0],
          explanation: 'Workflow management operates at the operational level: it coordinates who does what, in which order, with which resources, to execute defined business processes. Strategic and analytical work sits at higher abstraction levels.',
        },
        {
          kind: 'choice', id: 'A8', type: 'single', points: 3,
          text: 'A vendor claims its workflow management system (WfMS) offers all core capabilities. Which of the following is NOT a typical feature of a WfMS?',
          options: [
            'Providing step-by-step instructional guidance to help employees perform task content better.',
            'Routing work items to the correct role or person automatically.',
            'Tracking the status and history of each workflow instance.',
            'Enforcing deadlines and escalation rules.',
            'Supporting parallel and sequential task dependencies.',
          ],
          correct: [0],
          explanation: 'WfMS automate and coordinate process flows (routing, tracking, escalation, dependencies) but do NOT provide instructional guidance on how to perform work content. That role belongs to performance-support or knowledge-management systems.',
        },
        {
          kind: 'choice', id: 'A9', type: 'single', points: 3,
          text: 'Which of the following is NOT one of the workflow task types recognised in workflow management theory?',
          options: [
            'Predictive task',
            'Manual task',
            'Automated task',
            'Human task',
            'Message task',
          ],
          correct: [0],
          explanation: 'Standard workflow task types include manual tasks, automated tasks, human tasks, message tasks, and service tasks. "Predictive task" is not a recognised workflow task type — prediction is an analytics concept, not a workflow-process classification.',
        },
        {
          kind: 'choice', id: 'A10', type: 'single', points: 3,
          text: 'FAUBank is selecting an HRIS module to track employee skills, certifications, and career development plans. Which module handles these functions?',
          options: [
            'Talent management module.',
            'Payroll processing module.',
            'Time and attendance module.',
            'Benefits administration module.',
            'Workforce planning module.',
          ],
          correct: [0],
          explanation: 'The talent management module in an HRIS tracks skills, qualifications, certifications, training history, and career development plans. Payroll handles compensation; time/attendance tracks work hours; benefits admin manages employee benefits; workforce planning handles headcount forecasting.',
        },
      ],
    },
    {
      id: 'B',
      title: 'Part B — Social Media, Network Analysis, Employer Branding & Gamification',
      points: 30,
      tasks: [
        {
          kind: 'choice', id: 'B1', type: 'multiple', points: 3,
          text: 'FAUBank\'s ESM platform team runs a satisfaction survey. Which TWO of the following features would be classified as "basic (must-be) requirements" in the Kano model?',
          options: [
            'The chat function always connects within 2 seconds.',
            'The platform proactively suggests relevant colleagues based on current project assignments.',
            'User profiles are always up to date and contain accurate data.',
            'The platform sends personalised birthday notifications to colleagues.',
            'A real-time leaderboard highlights the top knowledge contributors of the week.',
          ],
          correct: [0, 2],
          explanation: 'Basic (must-be) Kano requirements are taken for granted: fast, reliable core functions (chat speed, data integrity). Absent, they cause strong dissatisfaction; present, they are not noticed. Colleague suggestions, birthday notifications, and real-time leaderboards are performance or excitement features.',
        },
        {
          kind: 'choice', id: 'B2', type: 'single', points: 3,
          text: 'In the FISH framework for analysing ESM behaviour, an employee who posts rarely but each post is widely shared and generates substantial discussion falls into which quadrant?',
          options: [
            'Influencer — low posting frequency, high reach and impact.',
            'Sharer — high posting frequency, high reach and impact.',
            'Lurker — low posting frequency, low reach and impact.',
            'Broadcaster — high posting frequency, low reach and impact.',
            'Observer — medium frequency, medium impact.',
          ],
          correct: [0],
          explanation: 'In the FISH (Frequency and Impact of Sharing Habits) framework, an influencer posts infrequently but with high reach or quality — they are key knowledge nodes despite low activity volume.',
        },
        {
          kind: 'choice', id: 'B3', type: 'single', points: 3,
          text: 'Employee E3 lies on the shortest path between many pairs of colleagues in the ESM network but has relatively few direct connections. Which centrality measure best captures E3\'s brokerage role?',
          options: [
            'Betweenness centrality — counts how often a node lies on the shortest path between other node pairs.',
            'Degree centrality — counts the number of direct connections.',
            'Closeness centrality — measures how quickly one can reach all other nodes.',
            'Eigenvector centrality — weighs connections by the importance of neighbours.',
            'PageRank — measures influence based on the quality of incoming links.',
          ],
          correct: [0],
          explanation: 'Betweenness centrality measures how many shortest paths between all other node pairs pass through a given node. High betweenness with low degree signals a structural broker — someone who controls information flow between otherwise disconnected groups.',
        },
        {
          kind: 'choice', id: 'B4', type: 'single', points: 3,
          text: 'Research on enterprise social networks finds that an employee\'s number of direct ESM connections is positively associated with which outcome?',
          options: [
            'Job satisfaction — employees with more connections tend to report higher job satisfaction.',
            'Salary increase — more connections lead to faster promotion cycles.',
            'Absenteeism — more connections create overload and additional sick days.',
            'Turnover intention — highly connected employees are more likely to seek outside opportunities.',
            'Work-life imbalance — more connections create demands outside working hours.',
          ],
          correct: [0],
          explanation: 'Studies of enterprise social networks consistently show that higher degree centrality — more direct connections — is associated with higher perceived job satisfaction. Connected employees benefit from information access, social support, and greater workplace visibility.',
        },
        {
          kind: 'calc', id: 'B5', unit: 'connections', answer: 4, tolerance: 0,
          points: 3,
          text: 'In the ESM network described in the scenario, employee E5 is directly connected to E2, E3, E4 and E7. What is the degree centrality of E5?',
          workedSolution: 'Degree centrality = number of direct connections. E5 links to E2, E3, E4, E7 → **4**.',
        },
        {
          kind: 'choice', id: 'B6', type: 'multiple', points: 3,
          text: 'Enterprise Social Media platforms are grouped into functional clusters. Which TWO of the following are NOT among the standard ESM functional clusters?',
          options: [
            'Financial reporting cluster',
            'Identity cluster',
            'Inventory management cluster',
            'Sharing cluster',
            'Presence cluster',
          ],
          correct: [0, 2],
          explanation: 'Standard ESM functional clusters include identity, presence, relationships, conversations, groups, sharing, reputation, and social search. Financial reporting and inventory management are ERP/SCM functions, not ESM clusters.',
        },
        {
          kind: 'choice', id: 'B7', type: 'single', points: 3,
          text: 'FAUBank\'s HR team wants to automatically suggest relevant internal job openings to employees based on their skills profiles and the behaviour of similar colleagues. Which AI approach best fits this use case?',
          options: [
            'Recommender system — suggests items most relevant to a user based on profile similarity or peer behaviour.',
            'Sentiment analysis — extracts emotional tone from free-text feedback.',
            'Computer vision — analyses images for pattern recognition.',
            'Natural language generation — automatically writes text from structured data.',
            'Anomaly detection — identifies unusual patterns in operational data streams.',
          ],
          correct: [0],
          explanation: 'A recommender system is the appropriate AI approach for matching employees to internal job openings: it uses content-based filtering (profile similarity) or collaborative filtering (peer behaviour) to surface relevant opportunities.',
        },
        {
          kind: 'choice', id: 'B8', type: 'single', points: 3,
          text: 'Which of the following best describes "employer branding" in the context of digital HRM?',
          options: [
            'A strategy to communicate and promote the organisation\'s identity and value proposition as an employer in order to attract and retain talent.',
            'A process for evaluating the financial performance of the HR department.',
            'A legal framework for employment contracts and statutory obligations.',
            'A performance management system for grading employee output against KPIs.',
            'A methodology for redesigning internal HR workflows and approval chains.',
          ],
          correct: [0],
          explanation: 'Employer branding involves building and communicating an organisation\'s identity, culture, and value proposition as a workplace. In the digital era, this uses social media, career portals, and employee review platforms to attract and retain talent.',
        },
        {
          kind: 'choice', id: 'B9', type: 'single', points: 3,
          text: 'FAUBank introduces gamification to its onboarding platform. Which combination of elements is most characteristic of game-based motivation design in HR contexts?',
          options: [
            'Points, badges, and leaderboards (PBL).',
            'Salary, bonuses, and promotions.',
            'KPIs, dashboards, and quarterly reviews.',
            'Policy manuals, org charts, and training certificates.',
            'Workflows, task templates, and escalation rules.',
          ],
          correct: [0],
          explanation: 'The classic gamification toolkit is points (immediate feedback on actions), badges (achievement recognition), and leaderboards (social comparison). These extrinsic motivators adapt game mechanics to non-game contexts such as HR onboarding.',
        },
        {
          kind: 'open', id: 'B11', points: 3,
          text: 'The FAUBank ESM network contains three clusters. Cluster A (nodes a1–a6) and Cluster B (nodes b1–b5) each have dense internal ties. Cluster C (nodes c1–c4) is similarly well-connected internally. The only connection between Cluster A and Cluster C is a single edge between nodes a5 and c1. There are no direct ties between Cluster B and Cluster C. Identify the structurally fragile (problematic) pattern in this network and explain why it represents a risk.',
          modelAnswer: 'The single edge **a5–c1** is the only tie connecting Cluster A to Cluster C, making it a **structural bridge** (also called a "bridge" or "cut edge"). If this one relationship breaks — because either employee leaves, changes roles, or the relationship deteriorates — Cluster A and Cluster C become completely disconnected, splitting the network in two. This is fragile because all information flow and collaboration between these two large groups depends on a single point of failure. A robust network design would have multiple redundant paths between clusters, so that removing any one edge does not disconnect major components.',
        },
      ],
    },
    {
      id: 'C',
      title: 'Part C — Data-Driven Approaches in HRM',
      points: 30,
      tasks: [
        {
          kind: 'choice', id: 'C1', type: 'single', points: 3,
          text: 'Which definition most accurately describes a recommender system?',
          options: [
            'A system that filters and presents items most relevant to a user, based on past behaviour, preferences, or similarity with other users.',
            'A system that translates natural language queries into database commands.',
            'A system that monitors employee productivity in real time.',
            'A system that automatically schedules shifts based on labour-law constraints.',
            'A system that generates performance appraisals using structured evaluation forms.',
          ],
          correct: [0],
          explanation: 'A recommender system predicts and surfaces items (courses, jobs, colleagues) that a given user is likely to value, using content-based filtering, collaborative filtering, or hybrid approaches. It does not handle scheduling, monitoring, or natural language processing.',
        },
        {
          kind: 'choice', id: 'C2', type: 'single', points: 3,
          text: 'FAUBank\'s training recommender struggles to suggest courses for a newly added "Agile Project Management" module that no employee has yet rated. Which recommender-system problem does this illustrate?',
          options: [
            'The new-item cold-start problem — the system cannot make predictions for items with no interaction history.',
            'The overfitting problem — the model memorises training data and fails to generalise.',
            'The data-sparsity problem — there are too few overall ratings in the user–item matrix.',
            'The scalability problem — the system cannot handle a large number of concurrent users.',
            'The grey-sheep problem — an atypical user does not fit any preference cluster.',
          ],
          correct: [0],
          explanation: 'The cold-start problem for new items arises because collaborative filtering relies entirely on user ratings. If nobody has yet rated a new course, there is no signal to build recommendations on. Solutions include falling back to content-based filtering or seeding ratings from domain experts.',
        },
        {
          kind: 'choice', id: 'C3', type: 'single', points: 3,
          text: 'FAUBank HR currently reports headcount and turnover percentages on a monthly basis from historical records. At which people-analytics maturity level does this activity sit?',
          options: [
            'Descriptive analytics — summarising what happened using historical data.',
            'Diagnostic analytics — investigating why things happened.',
            'Predictive analytics — forecasting what is likely to happen.',
            'Prescriptive analytics — recommending which action to take.',
            'Cognitive analytics — using AI to simulate complex human decision-making.',
          ],
          correct: [0],
          explanation: 'Reporting headcount and turnover from historical records is descriptive analytics — the first and most common maturity level. Diagnostic analytics investigates causal factors; predictive models forecast future states; prescriptive analytics recommends interventions.',
        },
        {
          kind: 'choice', id: 'C4', type: 'single', points: 3,
          text: 'In the IMPACT framework for people analytics, what does the "A" step represent?',
          options: [
            'Analyse — exploring the data to uncover patterns and generate insights.',
            'Allocate — distributing analytical resources across business units.',
            'Automate — replacing manual HR processes with algorithmic decision-making.',
            'Assess — evaluating employee performance scores at the individual level.',
            'Advocate — communicating HR analytics results to senior leadership.',
          ],
          correct: [0],
          explanation: 'The IMPACT cycle stands for: Identify the business question, Master the data, Provide statistical insights, Analyse findings, Communicate results, and Track outcomes. The "A" step is Analyse — exploring the data to uncover patterns and interpret their meaning.',
        },
        {
          kind: 'choice', id: 'C5', type: 'single', points: 3,
          text: 'A recruiter selects a candidate who brings skills the existing team lacks, but who shares the company\'s core values. Which type of person–organisation fit does this represent?',
          options: [
            'Complementary fit — the candidate\'s attributes supplement what the team already has.',
            'Supplementary fit — the candidate closely resembles current team members.',
            'Demands–abilities fit — the role requirements match the candidate\'s technical capabilities.',
            'Needs–supplies fit — the organisation meets the candidate\'s personal needs and values.',
            'Culture add — a concept unrelated to person–organisation fit frameworks.',
          ],
          correct: [0],
          explanation: 'Complementary fit occurs when a person fills a gap — providing skills or characteristics the team lacks while still aligning with overall culture. Supplementary fit means the person closely resembles existing members in skills and values.',
        },
        {
          kind: 'calc', id: 'C7', unit: 'rating', answer: 2.863, tolerance: 0.01,
          points: 9,
          text: 'User-based collaborative filtering. Predict Chris\'s rating for "Management". Means: ̅r=4.000 (Chris), 3.333 (Henrey), 2.667 (Susi). Similarities: sim(C,Henrey)=−0.874, sim(C,Susi)=0.986. Their Management deviations: Henrey 5−3.333=+1.667, Susi 2−2.667=−0.667. Round to 3 decimals.',
          workedSolution: 'pred(a,j) = ̅r_a + g·Σ w(a,i)(r_ij − ̅r_i), with g = 1/Σ|w|.\n\n- Weighted sum = (−0.874·1.667) + (0.986·−0.667) = −1.457 − 0.657 = **−2.114**\n- g = 1/(0.874 + 0.986) = 1/1.860 = **0.538**\n- pred = 4.000 + 0.538·(−2.114) = 4.000 − 1.137 = **2.863**',
        },
        {
          kind: 'calc', id: 'C8a', unit: 'MAE', answer: 1.9, tolerance: 0.05, points: 2,
          text: 'Predictions p and real ratings r for 10 items give absolute errors 0, 1, 4, 1, 4, 2, 1, 2, 3, 1. Compute the MAE (round to 1 decimal).',
          workedSolution: 'MAE = Σ|pᵢ−rᵢ|/n = (0+1+4+1+4+2+1+2+3+1)/10 = 19/10 = **1.9**',
        },
        {
          kind: 'calc', id: 'C8b', unit: 'MSE', answer: 5.3, tolerance: 0.05, points: 4,
          text: 'Using the same 10 prediction errors as in C8a (absolute errors: 0, 1, 4, 1, 4, 2, 1, 2, 3, 1), compute the Mean Squared Error (MSE). Round to 1 decimal.',
          workedSolution: 'MSE = Σ(pᵢ−rᵢ)²/n = (0²+1²+4²+1²+4²+2²+1²+2²+3²+1²)/10 = (0+1+16+1+16+4+1+4+9+1)/10 = 53/10 = **5.3**',
        },
      ],
    },
    {
      id: 'D',
      title: 'Part D — Challenges & Opportunities of E-HRM',
      points: 30,
      tasks: [
        {
          kind: 'choice', id: 'D1', type: 'single', points: 3,
          text: 'A 45-year-old experienced employee is influenced by usefulness, ease of use, peers and IT support when deciding whether to adopt a new system. Which theory best fits?',
          options: ['UTAUT', 'Theory of Reasoned Action (TRA)', 'Technology Acceptance Model (TAM)', 'Theory of Planned Behavior (TPB)', 'Multi-level model of user resistance'],
          correct: [0],
          explanation: 'UTAUT integrates performance expectancy, effort expectancy, social influence and facilitating conditions — matching a decision driven by several distinct factors at once.',
        },
        {
          kind: 'choice', id: 'D2', type: 'single', points: 3,
          text: 'The Theory of Reasoned Action (TRA) was specifically designed to explain which type of human behaviour?',
          options: [
            'Voluntary, intentional behaviour under the individual\'s conscious control.',
            'Habitual behaviour performed without conscious deliberation.',
            'Behaviour driven purely by biological or physiological impulses.',
            'Behaviour that is mandated by organisational policy and monitored by supervisors.',
            'Behaviour that emerges exclusively from group dynamics and peer pressure.',
          ],
          correct: [0],
          explanation: 'TRA is designed for rational, voluntary behaviours: it proposes that behavioural intention — driven by attitude toward the behaviour and subjective norms — predicts actual behaviour, assuming the person has volitional control over the act.',
        },
        {
          kind: 'choice', id: 'D3', type: 'single', points: 3,
          text: 'An employee believes the new HR self-service portal will help her complete routine tasks faster. Which UTAUT construct does this belief represent?',
          options: [
            'Performance expectancy — the degree to which using the system improves job performance.',
            'Effort expectancy — the degree to which the system is easy to use.',
            'Social influence — the degree to which important others believe she should use the system.',
            'Facilitating conditions — the degree to which infrastructure supports system use.',
            'Behavioural intention — the likelihood that she will actually use the system.',
          ],
          correct: [0],
          explanation: 'Performance expectancy in UTAUT captures the belief that using the technology will improve job performance (completing tasks faster). Effort expectancy relates to ease of use; social influence relates to peer/management pressure; facilitating conditions relate to infrastructure.',
        },
        {
          kind: 'choice', id: 'D4', type: 'single', points: 3,
          text: 'A long-tenured employee at FAUBank openly refuses to register on the new HCM portal, explicitly stating it is too complex and unnecessary. Which classification of user resistance best describes this behaviour?',
          options: [
            'Active, technology-related resistance — the employee explicitly rejects the system citing its characteristics.',
            'Passive, change-related resistance — the employee simply avoids the system without objecting openly.',
            'Covert resistance — the employee appears to adopt the system but uses hidden workarounds.',
            'Constructive resistance — the employee provides actionable feedback to help improve the system.',
            'Acceptance — the employee has not yet formed a view on the system.',
          ],
          correct: [0],
          explanation: 'This is active resistance (explicit refusal, openly stated) and technology-related (the reasons cited — complexity and perceived lack of value — concern the system\'s characteristics). Passive resistance involves avoidance without articulation; covert resistance masks non-adoption.',
        },
        {
          kind: 'choice', id: 'D5', type: 'single', points: 3,
          text: 'FAUBank appraises employees using adjectives like "proactive" and "reliable" rather than observed actions or measured outcomes. Which appraisal approach is this, and what is its main weakness?',
          options: [
            'Trait-based appraisal — subjective and difficult to defend legally because traits are not directly observable.',
            'Behaviour-based appraisal — focuses on specific observable actions rather than personality labels.',
            'Results-based appraisal — measures concrete outputs such as sales figures or project completions.',
            'Competency-based appraisal — aligns employee capability profiles with strategic requirements.',
            'Continuous appraisal — replaces annual reviews with ongoing real-time feedback cycles.',
          ],
          correct: [0],
          explanation: 'Trait-based appraisals assess personality characteristics (punctual, creative, reliable). The weakness is subjectivity: two raters may assess the same person differently, and the criteria are hard to justify in legal disputes because traits are not directly observable.',
        },
        {
          kind: 'choice', id: 'D6', type: 'multiple', points: 3,
          text: 'Research on e-HRM identifies multiple positive effects of HR technology adoption. Which TWO effects are most consistently documented in the literature?',
          options: [
            'Reduced administrative workload for HR staff through process automation.',
            'Complete elimination of bias in hiring and promotion decisions.',
            'Improved data accuracy and consistency in employee records.',
            'Full replacement of HR generalists by self-service technology.',
            'Guaranteed improvement in employee well-being and engagement.',
          ],
          correct: [0, 2],
          explanation: 'The two most consistently documented e-HRM effects are: (1) reduced administrative burden through automation, and (2) improved data accuracy because digital systems enforce input validation and a single-source-of-truth principle. Technology does not eliminate bias, replace HR generalists, or guarantee well-being improvements.',
        },
        {
          kind: 'choice', id: 'D7', type: 'single', points: 3,
          text: 'FAUBank deploys an HR chatbot for employee queries. Which dimension describes the chatbot\'s ability to understand ambiguous, free-form questions and respond coherently in natural language?',
          options: [
            'Conversational ability / natural language understanding (NLU) — interpreting and responding to free-form language input.',
            'Integration depth — the chatbot\'s ability to connect with backend HR and ERP systems.',
            'Personalisation — tailoring responses based on individual user history and preferences.',
            'Escalation logic — routing complex or sensitive queries to a human agent.',
            'Compliance enforcement — ensuring all responses adhere to labour law and GDPR.',
          ],
          correct: [0],
          explanation: 'Natural language understanding (NLU) is the core conversational dimension: it determines whether the chatbot can handle ambiguous, incomplete, or colloquial queries and return meaningful responses. Integration depth, personalisation, and escalation are separate, complementary capability dimensions.',
        },
        {
          kind: 'choice', id: 'D8', type: 'single', points: 3,
          text: 'What is described as a key intended organisational-level outcome of e-HRM implementation?',
          options: [
            'Strategic orientation — freeing HR professionals from administrative tasks to focus on value-adding strategic activities.',
            'Headcount reduction — eliminating all HR roles through full automation.',
            'Revenue generation — monetising HR data by selling it to third-party analytics firms.',
            'Compliance only — ensuring e-HRM satisfies data-protection and labour-law requirements.',
            'Employee surveillance — monitoring all employee actions continuously via HR technology.',
          ],
          correct: [0],
          explanation: 'A primary intended outcome of e-HRM is strategic orientation: by automating routine administration (payroll, leave requests, reporting), technology allows HR professionals to redirect time toward talent management, change leadership, and organisational design.',
        },
        {
          kind: 'choice', id: 'D9', type: 'single', points: 3,
          text: 'FAUBank wants to use AI to predict which employees are at risk of leaving. An ethics review board raises concerns. Which concern is most critical from a data-ethics perspective?',
          options: [
            'Lack of informed consent — employees may not know their data is used to infer intentions, potentially affecting career decisions made about them.',
            'The AI model is too expensive to deploy and maintain at scale.',
            'Prediction accuracy is too high, exposing the company to legal liability.',
            'The HR system vendor may not understand the bank\'s specific organisational culture.',
            'Using prediction models violates standard accounting and financial reporting standards.',
          ],
          correct: [0],
          explanation: 'The key data-ethics concern is transparency and informed consent: employees whose data feeds flight-risk models may face career consequences (e.g., withheld promotions) without knowing they were flagged. GDPR and HR ethics frameworks require transparency, purpose limitation, and proportionality.',
        },
        {
          kind: 'choice', id: 'D10', type: 'single', points: 3,
          text: 'In a digital HR transformation, which shift in the HR function\'s organisational role is most commonly described?',
          options: [
            'From administrative caretaker to strategic business partner — HR moves from processing transactions to co-designing the organisation.',
            'From business partner to financial controller — HR takes over budget management from the finance department.',
            'From strategic partner to operational support — HR re-centralises on routine administrative tasks.',
            'From people expert to IT department — HR staff retrain as software developers and data engineers.',
            'From compliance enforcer to marketing function — HR manages the company\'s external social media presence.',
          ],
          correct: [0],
          explanation: 'Digital HR transformation aims to shift the HR function from administrative/transactional work (records, payroll, forms) to strategic/consultative work (workforce planning, culture, talent strategy, organisational design) — consistent with Ulrich\'s HR business partner model.',
        },
      ],
    },
  ],
}

registerMockExam('ehrm', exam)
